# Java是最好的语言
server:
  port: 7777
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/fly?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    validation-query: SELECT 1
    validation-query-timeout: 5000
    test-on-borrow: true
    test-on-connect: true